### ISSUE TITLE
Allow escaping delimiters

### ISSUE THREAD

**Issue by tofof** [Sleuteltje/plugin.video.youtubelibrary#5]
The "Remove" and "Strip" functions use `|` as a delimiter. However, it doesn't appear to be possible to escape the delimiter - I have tried a backslash `\|` and doubling `||` but neither worked. 

Motivation, of course, is that I have a [series](https://www.youtube.com/playlist?list=PLTur7oukosPFINuomVBIGR-UlHWpN5KIk) with redundant title text (` | Rooster Teeth`) including `|` that I'd like to be able to remove.

Nice feature otherwise, though - really helps clean up the list of shows.

**Comment by tofof** [comment]
Fix in progress.

**Comment by tofof** [comment]
@Sleuteltje 
I have this finished and working well. 😁
In the process, it's trivial to add an extra option - similar to 'strip' but stripping out from the beginning of the text to the match, instead of from the match to the end.

However, I'm trying to add a couple new settings to control the new option, and I'm getting problems when trying to use already-created playlists that are missing those settings.

In other words, [settings.find](https://github.com/tofof/plugin.video.youtubelibrary/blob/2ffa91aee34f8396552ac3c1c64833578dffecc0/resources/lib/generators.py#L908-L913) dies when encountering the new settings.  
To be clear, I've [inserted the setting](https://github.com/tofof/plugin.video.youtubelibrary/commit/121e9d6c73801dc069bf70c853d7a61a7de368f6) everywhere it seems to belong..

It doesn't seem like there's anywhere during a playlist update that checks to make sure there aren't new settings that need to be inserted. 🤔
Am I missing something? What's your process to add a new setting?

**Comment by tofof** [comment]
I'm writing a settings validation method to handle the new complication. I'm still working on integrating it into the codebase and getting it fully tested.

In the meantime, I'll spin off a PR without the new option so that you can review that piece independently.

**Comment by Sleuteltje** [comment]
Hey, good work 😀 ! Whenever i put in a new setting i've used "if settings.find('<SETTING>') is not None:", as you can see demonstrated here: https://bitbucket.org/Sleuteltje/plugin.video.youtubelibrary/commits/bec7fb7d6c075da6796799408f9caf98b83f4b9e (it was on bitbucket before i moved to github). And used a default for when the setting was not found. 

Come to think of it, we can indeed better replace settings.find() with a better fallback function that will function something like this:

```
function find_setting(setting, settings):
          if settings.find(setting) is None:
                     #Get the default setting from the addonsettings
                     return dev.getAddonSetting(setting)
          return settings.find(setting).text
```
and replace all settings.find() references accordingly. Then we are future proof for new settings and its more logical it fallsback to addonsettings defaults rather then hardcoded defaults.


I hope you can find your way around my code a bit :)

**Comment by tofof** [comment]
I am indeed doing something similar to that. The technique I went with was to just check all settings when they're first loaded - for example, in `update_playlist` (which then passes them in turn to `write_tvshow_nfo` and from there to `get_tags_xml`).

This has a couple advantages: 1) avoids re-checking the same setting on every use 2) allows some settings to remain completely unset if desired (like 'update_gmt') and 3) obviously doesn't require finding and replacing all the uses of `settings.find()`. 

Importantly, it also centralizes where the defaults are, so that you avoid the situation where you're [supplying a default alongside the use](https://bitbucket.org/Sleuteltje/plugin.video.youtubelibrary/commits/bec7fb7d6c075da6796799408f9caf98b83f4b9e#Lresources/lib/service.pyT108) -- that gets very messy when you later want to change that default and you have to look in all the places it might have been supplied. 

Also, just FYI, it's not quite as simple as the `dev.getAddonSetting(setting)` as you have above, because [some settings don't use what that method returns](https://github.com/Sleuteltje/plugin.video.youtubelibrary/blob/master/resources/lib/m_xml.py#L352-L354). 

This is really a discussion for the PR after #8; it is self-contained and doesn't need any of the settings changes.
